#!/bin/sh

function _crontest() {
	if [ "$(uci get automail.@automail[0].f1_list)" != "*" ];then
		_cron_f1="$(uci get automail.@automail[0].sch_f1)"
	else
		_cron_f1="*"
	fi
	if [ "$(uci get automail.@automail[0].f2_list)" != "*" ];then
		_cron_f2="$(uci get automail.@automail[0].sch_f2)"
	else
		_cron_f2="*"
	fi
	if [ "$(uci get automail.@automail[0].f3_list)" != "*" ];then
		_cron_f3="$(uci get automail.@automail[0].sch_f3)"
	else
		_cron_f3="*"
	fi
	if [ "$(uci get automail.@automail[0].f4_list)" != "*" ];then
		_cron_f4="$(uci get automail.@automail[0].sch_f4)"
	else
		_cron_f4="*"
	fi
	if [ "$(uci get automail.@automail[0].f5_list)" != "*" ];then
		_cron_f5="$(uci get automail.@automail[0].f5_list)"
	else
		_cron_f5="*"
	fi

	if [ ! -n "$(cat /etc/crontabs/root | grep automail.sh)" ];then
		echo "$_cron_f1 $_cron_f2 $_cron_f3 $_cron_f4 $_cron_f5 /usr/automail/automail.sh" >> /etc/crontabs/root
	else
		sed -i "$(cat /etc/crontabs/root | grep -n automail.sh | tail -n1 | cut -d ':' -f1)d" /etc/crontabs/root
		echo "$_cron_f1 $_cron_f2 $_cron_f3 $_cron_f4 $_cron_f5 /usr/automail/automail.sh" >> /etc/crontabs/root
	fi
	/etc/init.d/cron restart
}

if [ "$(uci get automail.@automail[].schedules)" == "1" ];then
	if [ -n "$(cat /etc/crontabs/root | grep automail.sh | grep -n "^#" | cut -d ':' -f1)" ];then
		for i in $(cat /etc/crontabs/root | grep -n automail.sh | cut -d ':' -f1);do
			sed -i "${i}s/^#//" /etc/crontabs/root
		done
	fi
	_crontest
else
	if [ ! -n "$(cat /etc/crontabs/root | grep automail.sh | grep -n "^#" | cut -d ':' -f1)" ];then
		for i in $(cat /etc/crontabs/root | grep -n automail.sh | cut -d ':' -f1);do
			sed -i "${i}s/^/#/" /etc/crontabs/root
		done
		/etc/init.d/cron restart
	fi
fi

