#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2011 OpenWrt.org

START=83

USE_PROCD=1
PROG=/usr/bin/GWAppCloud
#PROCD_DEBUG=1

start_service() {
	local device_type
	. /usr/share/libubox/jshn.sh
	json_load "$(cat /etc/IoT/Model.json)"
	json_get_var device_type TypeId
	if [ "$device_type" == "32766" ]; then
		echo "SubGateway type, skip GWServer."
		# 如果是子网关，则不运行GWAppCloud程序
		return
	fi

	local addr
	# 读取/etc/config/gwserver 配置文件的服务器地址
	addr="$(uci get gwserver.config.address -q)"

	procd_open_instance
	procd_set_param command "$PROG"
	[ -z "$addr" ] || {
		procd_append_param command -i "$addr"
	}
	procd_append_param command -d
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-0}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/GWAppCloud.pid
	procd_close_instance
}

stop_service() {
	service_stop "$PROG"
}
