---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2018/6/20 16:45
---

module("luci.controller.admin.common", package.seeall)

function index()
    entry({"admin", "common"}, template("new_siwifi/common_settings/common_settings")).leaf = true;
end