#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/ramips.sh
. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(ramips_board_name)

case "$board" in
all0239-3g | \
all0256n | \
all5002)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x10000" "0x10000"
	;;
c-life-xg1)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x20000" "0x20000"
	;;
linkits7688 | \
linkits7688d | \
wsr-600 | \
wsr-1166 | \
mac1200rv2 | \
wdr5620v1 | \
wdr5640v1 | \
360p2 | \
br6425 | \
mi-router-4c | \
miwifi-nano)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x1000" "0x10000"
	;;
mir3g | \
mi-router-ac2100 | \
redmi-router-ac2100)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x1000" "0x20000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
