#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	enabled=$(uci get i2c-ssd1306.@i2c-ssd1306[0].enabled)
	if [ $enabled -eq 0 ]; then
		exit 0
	fi

	procd_open_instance
	procd_set_param command /usr/sbin/i2c_ssd1306 \
		-i "$(uci get i2c-ssd1306.@i2c-ssd1306[0].i2c_bus)" \
		-a "$(uci get i2c-ssd1306.@i2c-ssd1306[0].i2c_address)" \
		-l "$(uci get i2c-ssd1306.@i2c-ssd1306[0].log_file)"
    
	procd_set_param respawn
	procd_close_instance

	if [ ! -f "$(uci get i2c-ssd1306.@i2c-ssd1306[0].log_file)" -o ! -s "$(uci get i2c-ssd1306.@i2c-ssd1306[0].log_file)" ]; then
		echo "  \$(date +%m-%d\ %H:%M:%S)" > /var/log/ssd1306.log
		echo "  HELLO, OPENWRT!" >> /var/log/ssd1306.log
		echo "  LAN IP:\$(ifstatus lan | jsonfilter -e '@[\"ipv4-address\"][0].address')" >> /var/log/ssd1306.log
		echo "  WAN IP:\$(ifstatus wan | jsonfilter -e '@[\"ipv4-address\"][0].address')" >> /var/log/ssd1306.log
	fi
}

stop_service() {
    killall i2c_ssd1306
}

restart() {
    stop
    start
}

