#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2012 OpenWrt.org

START=99
USE_PROCD=1

APP=gmediarender
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
suffix="$(uci get system.@system[0].hostname)"
dlnaname=${APP}-${suffix}

start_service() {
	procd_open_instance

	procd_set_param command /usr/bin/$APP -f ${dlnaname}

	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	service_stop /usr/bin/$APP
}
