#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2022 OpenWrt.org

START=99

PROG=/usr/bin/pppwn

start() {
	config_load "pppwn"
	
	config_get "source" "config" "source"
	config_get "fwver" "config" "fwver"
	
	local enable
	config_get_bool enable config enable 0
	
	[ "${enable}" -gt 0 ] || return

	$PROG --interface $source --fw $fwver --stage1 "/etc/pppwn/stage1_$fwver.bin" --stage2 "/etc/pppwn/stage2_$fwver.bin" -a > /var/log/pppwn.log &

	if [ -e "/usr/bin/pppwnlog" ];then
		if [ -z "$(busybox ps | grep pppwnlog | grep -v grep)" ];then
			pppwnlog
		fi
	fi

}

stop() {
    busybox ps | grep -v "grep" | grep "$PROG" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1 &
    echo "" > /var/log/pppwn.log
}
