#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2022 OpenWrt.org

START=99
USE_PROCD=1

PROG="/usr/bin/pppwn"

start_service() {
    config_load "pppwn"

    config_get "source" "config" "source"
    config_get "fwver" "config" "fwver"

    local enable
    config_get_bool enable config enable 0

    [ "${enable}" -gt 0 ] || return

    procd_open_instance
    procd_set_param command $PROG --interface "$source" --fw "$fwver" --stage1 "/etc/pppwn/stage1_$fwver.bin" --stage2 "/etc/pppwn/stage2_$fwver.bin" -a
    procd_set_param stdout 1
    #procd_set_param stderr 1
    procd_set_param respawn                                                                                                         
    procd_close_instance  
}

stop_service() {
    service_stop $PROG
}

