#!/bin/sh

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

function look30sec() {
	sleep 8
	adb -s ${adbclient}:5555 shell input swipe 835 1050 835 700
	sleep 8
	adb -s ${adbclient}:5555 shell input swipe 835 1050 835 700
	sleep 8
	adb -s ${adbclient}:5555 shell input swipe 835 1050 835 700
	sleep 8
}

adb connect ${adbclient}:5555
sleep 2

adb -s ${adbclient}:5555 shell am start -n com.taobao.live/.home.activity.TaoLiveHomeActivity
sleep 5

adb -s ${adbclient}:5555 shell input tap 950 2045
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 2045
sleep 3

adb -s ${adbclient}:5555 shell input tap 535 1525
sleep 3
adb -s ${adbclient}:5555 shell input tap 535 1280
sleep 3
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 950 900
sleep 3

adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3

adb -s ${adbclient}:5555 shell input tap 950 300
adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 300
adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 300
sleep 3

adb -s ${adbclient}:5555 shell input tap 780 1280
sleep 5

adb -s ${adbclient}:5555 shell input tap 155 1625
sleep 3

adb -s ${adbclient}:5555 shell input tap 858 1568
sleep 5

adb -s ${adbclient}:5555 shell input tap 220 1190
sleep 3

adb -s ${adbclient}:5555 shell input tap 550 1980
sleep 5

adb -s ${adbclient}:5555 shell input tap 385 1660
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 12

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 5
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 12

adb -s ${adbclient}:5555 shell input tap 550 2000
sleep 3

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 5

ltimes=0
while [ $ltimes -lt 3 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 1060
	sleep 3
	look30sec
	sleep 2
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done

ltimes=0
while [ $ltimes -lt 3 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 1060
	sleep 3
	look30sec
	sleep 2
	look30sec
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done

ltimes=0
while [ $ltimes -lt 5 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 1060
	sleep 3
	look30sec
	sleep 2
	look30sec
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 7 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 11 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
dianzan=0
while [ $dianzan -lt 22 ]
do
	adb -s ${adbclient}:5555 shell input tap 1000 2025
	sleep 1
	dianzan=$(echo `expr $dianzan + 1`)
done
sleep 1
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 5
adb -s ${adbclient}:5555 shell input tap 770 1960
sleep 7

adb -s ${adbclient}:5555 shell input tap 530 1515
sleep

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 17 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 21 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 1
ltimes=0
while [ $ltimes -lt 7 ]
do
	adb -s ${adbclient}:5555 shell input swipe 535 1500 535 1100
	sleep 5
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 155 1625
sleep 2

adb -s ${adbclient}:5555 shell input tap 858 1568
sleep 5

adb -s ${adbclient}:5555 shell input tap 550 1190
sleep 3

adb -s ${adbclient}:5555 shell input tap 550 1980
sleep 5

adb -s ${adbclient}:5555 shell input tap 635 1845

