#!/bin/sh

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

function look30sec() {
	sleep 10
	adb -s ${adbclient}:5555 shell input swipe 835 1050 835 700
	sleep 10
	adb -s ${adbclient}:5555 shell input swipe 835 1050 835 700
	sleep 10
}

adb connect ${adbclient}:5555
sleep 2

# 启动点淘
adb -s ${adbclient}:5555 shell am start -n com.taobao.live/.home.activity.TaoLiveHomeActivity
sleep 5

# 进入我的
adb -s ${adbclient}:5555 shell input tap 950 2045
sleep 3

#进入元宝中心
adb -s ${adbclient}:5555 shell input tap 950 900
sleep 3

#关闭可能出现的弹出框
adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3

#领取金蛋
adb -s ${adbclient}:5555 shell input tap 950 300
adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 300
adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 300
sleep 3

#进入打工赚元宝
adb -s ${adbclient}:5555 shell input tap 780 1280
sleep 5

#领取体力
adb -s ${adbclient}:5555 shell input tap 155 1625
sleep 3

#去打工赚钱
adb -s ${adbclient}:5555 shell input tap 858 1568
sleep 5

#选择歌手
adb -s ${adbclient}:5555 shell input tap 220 1190
sleep 3

#开始打工
adb -s ${adbclient}:5555 shell input tap 550 1980
sleep 5

#赚体力
adb -s ${adbclient}:5555 shell input tap 385 1660
sleep 3

#依次做任务
#任务1-去芭芭农场施肥
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 12

#完成一次施肥
adb -s ${adbclient}:5555 shell input tap 550 2000
sleep 3

#任务1完成-从芭芭农场返回点淘任务列表
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 5


#看直播任务1-30秒3次
ltimes=0
while [ $ltimes -lt 3 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 1060
	sleep 3
	look30sec
	sleep 2
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done

#看直播任务2-60秒3次
ltimes=0
while [ $ltimes -lt 3 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 1060
	sleep 3
	look30sec
	sleep 2
	look30sec
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done

#看直播任务3-60秒5次
ltimes=0
while [ $ltimes -lt 5 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 1060
	sleep 3
	look30sec
	sleep 2
	look30sec
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done



#看直播任务4-3分钟1次
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 7 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

#看直播任务5-5分钟1次
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 11 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

#看直播任务6-点赞20次
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
dianzan=0
while [ $dianzan -lt 22 ]
do
	adb -s ${adbclient}:5555 shell input tap 1000 2025
	sleep 1
	dianzan=$(echo `expr $dianzan + 1`)
done
sleep 1
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

#看直播任务7-闲鱼
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 5
adb -s ${adbclient}:5555 shell input tap 770 1960
sleep 7
#闲鱼每日签到
adb -s ${adbclient}:5555 shell input tap 530 1515
sleep
#返回点淘继续做任务
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

#看直播任务8-8分钟1次
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 17 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

#看直播任务9-10分钟1次
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 3
ltimes=0
while [ $ltimes -lt 21 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

#看直播任务10-浏览好货卖场30秒
adb -s ${adbclient}:5555 shell input tap 910 1060
sleep 1
ltimes=0
while [ $ltimes -lt 7 ]
do
	adb -s ${adbclient}:5555 shell input swipe 535 1500 535 1100
	sleep 5
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

#领取体力
adb -s ${adbclient}:5555 shell input tap 155 1625
sleep 2

#去打工赚钱
adb -s ${adbclient}:5555 shell input tap 858 1568
sleep 5

#选择厨师
adb -s ${adbclient}:5555 shell input tap 550 1190
sleep 3

#开始打工
adb -s ${adbclient}:5555 shell input tap 550 1980
sleep 5

#签到
adb -s ${adbclient}:5555 shell input tap 635 1845

#任务完成
