#!/bin/sh

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

function redo() {
	sleep 6
	adb -s ${adbclient}:5555 shell input swipe 550 1398 550 670
	sleep 2
	adb -s ${adbclient}:5555 shell input swipe 550 1398 550 670
	sleep 2
	adb -s ${adbclient}:5555 shell input swipe 550 1398 550 670
	sleep 5
	adb -s ${adbclient}:5555 shell input tap 945 1015
}

adb connect ${adbclient}:5555
sleep 2

adb -s ${adbclient}:5555 shell am start -n com.jd.jdlite/.MainActivity
sleep 7

adb -s ${adbclient}:5555 shell input tap 105 605
sleep 7

adb -s ${adbclient}:5555 shell input tap 525 1100
sleep 3
adb -s ${adbclient}:5555 shell input tap 525 1100
sleep 3
adb -s ${adbclient}:5555 shell input tap 525 1100
sleep 3

adb -s ${adbclient}:5555 shell input tap 945 877
sleep 7

adb -s ${adbclient}:5555 shell input tap 545 950
sleep 5

adb -s ${adbclient}:5555 shell input tap 919 1662
sleep 6

ltimes=0
while [ $ltimes -lt 50 ]
do
	redo
	sleep 2
	ltimes=$(echo `expr $ltimes + 1`)
done

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 970 2030
sleep 3

adb -s ${adbclient}:5555 shell input tap 320 1130
sleep 5
adb -s ${adbclient}:5555 shell input tap 915 720

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 110 1130
sleep 5
adb -s ${adbclient}:5555 shell input tap 545 1350
sleep 5
adb -s ${adbclient}:5555 shell input tap 540 1466
sleep 5
adb -s ${adbclient}:5555 shell input tap 537 1380
sleep 5
adb -s ${adbclient}:5555 shell input tap 339 1500
sleep 5
adb -s ${adbclient}:5555 shell input tap 540 1635
sleep 5
adb -s ${adbclient}:5555 shell input tap 537 1437
sleep 3
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

