#!/bin/sh
. /usr/ffmpegtool/commonfunc

testdestpath

param_format="$(uci get ffmpegtool.@ffmpegtool[0].audio_format)"
param_rate=""
param_channel=""
param_starttime=""
param_endtime=""
param_tone=""
param_speed=""
param_volume=""
param_title=""
param_copy=""

if [ "$(uci get ffmpegtool.@ffmpegtool[0].sampling_rate)" != "none" ];then
	param_rate="-ar $(uci get ffmpegtool.@ffmpegtool[0].sampling_rate)"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_channel)" != "none" ];then
	param_channel="-ac $(uci get ffmpegtool.@ffmpegtool[0].audio_channel)"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" != "none" ];then
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "sharp(44100Hz)" ];then
		param_tone="asetrate=44100*2^(1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "sharp(22050Hz)" ];then
		param_tone="asetrate=22050*2^(1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "rasing whole tone(44100Hz)" ];then
		param_tone="asetrate=44100*2^(2/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "rasing whole tone(22050Hz)" ];then
		param_tone="asetrate=22050*2^(2/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "flat(44100Hz)" ];then
		param_tone="asetrate=44100*2^(-1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "flat(22050Hz)" ];then
		param_tone="asetrate=22050*2^(-1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "falling whole tone(44100Hz)" ];then
		param_tone="asetrate=44100*2^(-2/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "falling whole tone(22050Hz)" ];then
		param_tone="asetrate=22050*2^(-2/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "special-1(44100Hz)" ];then
		param_tone="asetrate=44100*2^(4/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "special-1(22050Hz)" ];then
		param_tone="asetrate=22050*2^(4/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "special-2(44100Hz)" ];then
		param_tone="asetrate=44100*2^(-4/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "special-2(22050Hz)" ];then
		param_tone="asetrate=22050*2^(-4/12),"
	fi
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].a_speed_governing)" != "none" ];then
	_speed="$(uci get ffmpegtool.@ffmpegtool[0].a_speed_governing)"
	param_speed="atempo=${_speed},"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" != "none" ];then
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "standard" ];then
		param_volume="loudnorm=i=-14:tp=0.0"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "+15dB" ];then
		param_volume="volume=15dB"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "+10dB" ];then
		param_volume="volume=10dB"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "+5dB" ];then
		param_volume="volume=5dB"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "-5dB" ];then
		param_volume="volume=-5dB"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "-10dB" ];then
		param_volume="volume=-10dB"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "0.2" ];then
		param_volume="volume=0.2"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "0.5" ];then
		param_volume="volume=0.5"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "1.5" ];then
		param_volume="volume=1.5"
	fi
fi

if [ "$param_tone" == "" -a "$param_speed" == "" -a "$param_volume" == "" ];then
	audios_param=""
else
	audios_param="$(echo "-filter_complex:a $param_tone$param_speed$param_volume" | sed 's/,$//')"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_copy)" == "1" ];then
	param_copy="-acodec copy"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_sept_silence)" == "1" ];then
	input_file="$(uci get ffmpegtool.@ffmpegtool[0].audio_sept_silence_input)"
	THRESHOLD="$(uci get ffmpegtool.@ffmpegtool[0].audio_sept_silence_threshold)"
	SILENCE_DURATION="$(uci get ffmpegtool.@ffmpegtool[0].audio_sept_silence_duration)"
	start_time=0
	end_time=0
	durations=0
	output_file_prefix=0
	ffmpeg -i "$input_file" -af "silencedetect=n=$THRESHOLD:d=$SILENCE_DURATION" -f null - 2>&1 |
	while read line; do
	    if [[ "$line" == *[Ss]ilence_end* ]]; then
	        start_time=$end_time
	        end_time=$(echo "$line" | cut -d '|' -f1 | cut -d ':' -f2 | cut -d '.' -f1 )
		if [ $end_time -lt $start_time ];then
			end_time=$start_time
		fi
	        durations=$(expr $end_time - $start_time)
	        if [ ! -z $(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path) ];then
	    		output_file="$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/${output_file_prefix}.output_sept.$param_format" 
	        else
	    		output_file="$(dirname $input_file)/${output_file_prefix}.output_sept.$param_format"    
	        fi
	        echo "${input_file}文件分割处理中...，输出:$(basename ${output_file})" >> /tmp/ffmpeg.log
	        ffmpeg -loglevel quiet -i "$input_file" -ss $start_time $param_rate $param_channel $audios_param $param_title $param_copy -t $durations "$output_file" -y
		ffmpeg -loglevel error -i "$output_file" -c copy -f null /dev/null
		if [ $? -ne 1 ]; then
		        output_file_prefix=$(expr $output_file_prefix + 1)
		fi
	    fi
	done
	echo "分割完毕!" >> /tmp/ffmpeg.log
	ucidefault
	exit 0
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_separate)" == "1" ];then
	input_file="$(uci get ffmpegtool.@ffmpegtool[0].audio_sept_input)"
	start_time=0
	durations=0
	timespinner=$(uci get ffmpegtool.@ffmpegtool[0].audio_sept_timespinner)
	output_file_prefix=1
	segments=$(uci get ffmpegtool.@ffmpegtool[0].audio_sept_segment | sed 's/,/ /g')
	for i in ${segments};do
	    start_time="$(expr ${start_time} + ${durations})"
	    if [ $(echo ${i} | tr -cd ':' | wc -c) -eq 2 ];then
	    	hourtomin=$(expr $(echo ${i} | cut -d ':' -f1) \* 60)
	    	mintosec=$(expr $(expr ${hourtomin} + $(echo ${i} | cut -d ':' -f2)) \* 60)
	    	durations=$(expr $(echo ${i} | cut -d ':' -f3) + ${mintosec} + ${timespinner})
	    elif [ $(echo ${i} | tr -cd ':' | wc -c) -eq 1 ];then
	    	mintosec=$(expr $(echo ${i} | cut -d ':' -f1) \* 60)
	    	durations=$(expr $(echo ${i} | cut -d ':' -f2) + ${mintosec} + ${timespinner})
	    else
	    	durations=$(expr ${i} + ${timespinner})
	    fi
	    if [ ! -z $(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path) ];then
	    	output_file="$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/${output_file_prefix}.output_sept.$param_format" 
	    else
	    	output_file="$(dirname $input_file)/${output_file_prefix}.output_sept.$param_format"    
	    fi
	    echo "${input_file}文件分割处理中...，输出:$(basename ${output_file})" >> /tmp/ffmpeg.log
	    if [ $(echo "${input_file##*.}") = $param_format ];then
	    	ffmpeg -i "$input_file" -ss ${start_time} -t $durations -c copy "$output_file" -y
	    else
	    	ffmpeg -i "$input_file" -ss ${start_time} -t $durations "$output_file" -y
	    fi
	    output_file_prefix=$(expr $output_file_prefix + 1)
	done 
	echo "分割完毕!" >> /tmp/ffmpeg.log
	ucidefault
	exit 0
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_merge)" == "1" ];then
	input1=$(uci get ffmpegtool.@ffmpegtool[0].audio_input1)
	input2=$(uci get ffmpegtool.@ffmpegtool[0].audio_input2)
	echo " $input1 ----> 音频合并中 <---- $input2 " >> /tmp/ffmpeg.log
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].enable_amix)" == "one by one" ];then
		ffmpeg -i "${input1}" -i "${input2}" -filter_complex "[0:0][1:0] concat=n=2:v=0:a=1[a]" -map [a] "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/merge-$(date +%s).$param_format" -y
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].enable_amix)" == "mix1" ];then
		ffmpeg -i "${input1}" -i "${input2}" -filter_complex amix=inputs=2:duration=longest "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/merge-$(date +%s).$param_format" -y
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].enable_amix)" == "mix2" ];then
		ffmpeg -i "${input1}" -i "${input2}" -filter_complex "amerge=inputs=2,pan=stereo|c0<c0+c1|c1<c2+c3" "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/merge-$(date +%s).$param_format" -y
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].enable_amix)" == "mix3" ];then
		ffmpeg -i "${input1}" -i "${input2}" -filter_complex amerge=inputs=2 "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/merge-$(date +%s).$param_format" -y
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].enable_amix)" == "mix4" ];then
		ffmpeg -i "${input1}" -t $(uci get ffmpegtool.@ffmpegtool[0].audio_null) -f s16le -acodec pcm_s16le -i /dev/zero -i "${input2}" -filter_complex "[0:0][1:0][2:0] concat=n=3:v=0:a=1[a]" -map [a] "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/merge-$(date +%s).$param_format" -y
	fi
	echo "合并完毕!" >> /tmp/ffmpeg.log
	ucidefault
	exit 0
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].dest_select)" == "streaming media server" ];then
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "one file" ];then
		while true;do
			srctarget="$(uci get ffmpegtool.@ffmpegtool[0].src_file_path)"
			ffprobe "$srctarget" > /tmp/ffmpeg.log 2>&1
			echo "$srctarget ---- 推流中..." >> /tmp/ffmpeg.log
			if [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "rtmp server" ];then
				ffmpeg -re -i "$srctarget" $audios_param -vn $param_rate $param_channel $param_copy -f flv "$(uci get ffmpegtool.@ffmpegtool[0].rtmp_server_url)"
			elif [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "icecast server" ];then
				ffmpeg -re -i "$srctarget" $audios_param -vn $param_rate $param_channel $param_copy -f mp3 "$(uci get ffmpegtool.@ffmpegtool[0].icecast_server_url)"
			fi
		done
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "all files in the directory" ];then
		srctarget="$(ls $(uci get ffmpegtool.@ffmpegtool[0].src_directory_path))"
		while true;do
			for i in $srctarget;do
				ffprobe "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" > /tmp/ffmpeg.log 2>&1
				echo "$i ---- 推流中..." >> /tmp/ffmpeg.log
				if [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "rtmp server" ];then
					ffmpeg -re -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $audios_param -vn $param_rate $param_channel $param_copy -f flv "$(uci get ffmpegtool.@ffmpegtool[0].rtmp_server_url)"
				elif [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "icecast server" ];then
					ffmpeg -re -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $audios_param -vn $param_rate $param_channel $param_copy -f mp3 "$(uci get ffmpegtool.@ffmpegtool[0].icecast_server_url)"
				fi
			done
		done
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "streaming media" ];then
		while true;do
			srctarget="$(uci get ffmpegtool.@ffmpegtool[0].src_stream_path)"
			ffprobe "$srctarget" > /tmp/ffmpeg.log 2>&1
			echo "$srctarget ---- 推流中..." >> /tmp/ffmpeg.log
			if [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "rtmp server" ];then
				ffmpeg -re -i "$srctarget" $audios_param -vn $param_rate $param_channel $param_copy -f flv "$(uci get ffmpegtool.@ffmpegtool[0].rtmp_server_url)"
			elif [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "icecast server" ];then
				ffmpeg -re -i "$srctarget" $audios_param -vn $param_rate $param_channel $param_copy -f mp3 "$(uci get ffmpegtool.@ffmpegtool[0].icecast_server_url)"
			fi
		done
	fi
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "one file" ];then
	srctarget="$(uci get ffmpegtool.@ffmpegtool[0].src_file_path)"
	ffprobe "$srctarget" > /tmp/ffmpeg.log 2>&1
	time_work_a
	if [ ! -n "$(cat /tmp/ffmpeg.log | grep title)" -a "$(uci get ffmpegtool.@ffmpegtool[0].audio_addtitle)" == "1" ];then
		param_title="-metadata title=$(uci get ffmpegtool.@ffmpegtool[0].src_file_path | cut -d '/' -f$(expr $(uci get ffmpegtool.@ffmpegtool[0].src_file_path | grep -o / | wc -l) + 1) | cut -d '.' -f1)"
	fi
	echo "$srctarget ---- 转换中..." >> /tmp/ffmpeg.log
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_titleisname)" == "1" ];then
		param_title="$(cat /tmp/ffmpeg.log | grep title | awk '{print$3}')"
		ffmpeg $param_starttime $param_endtime -i "$srctarget" $param_rate $param_channel $audios_param $param_copy "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$param_title.$param_format" -y
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_add_silence)" == "1" ];then
		silence_d="$(uci get ffmpegtool.@ffmpegtool[0].audio_silence_duration)"
		ffmpeg -i "$srctarget" -af "adelay=${silence_d}|${silence_d}" "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(uci get ffmpegtool.@ffmpegtool[0].src_file_path | cut -d '/' -f$(expr $(uci get ffmpegtool.@ffmpegtool[0].src_file_path | grep -o / | wc -l) + 1) | cut -d '.' -f1).$param_format" -y
	else
		ffmpeg $param_starttime $param_endtime -i "$srctarget" $param_rate $param_channel $audios_param $param_copy $param_title "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(uci get ffmpegtool.@ffmpegtool[0].src_file_path | cut -d '/' -f$(expr $(uci get ffmpegtool.@ffmpegtool[0].src_file_path | grep -o / | wc -l) + 1) | cut -d '.' -f1).$param_format" -y
	fi
	echo "转换完成!" >> /tmp/ffmpeg.log
elif [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "all files in the directory" ];then
	srctarget="$(ls $(uci get ffmpegtool.@ffmpegtool[0].src_directory_path))"
	for i in $srctarget;do
		ffprobe "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" > /tmp/ffmpeg.log 2>&1
		time_work_a
		if [ ! -n "$(cat /tmp/ffmpeg.log | grep title)" -a "$(uci get ffmpegtool.@ffmpegtool[0].audio_addtitle)" == "1" ];then
			param_title="-metadata title="$(echo "$i" | cut -d '.' -f1)""
		fi
		echo "$i ---- 转换中..." >> /tmp/ffmpeg.log
		if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_titleisname)" == "1" ];then
			ffmpeg $param_starttime $param_endtime -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $param_rate $param_channel $audios_param $param_copy "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$param_title.$param_format" -y
		elif [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_add_silence)" == "1" ];then
			silence_d="$(uci get ffmpegtool.@ffmpegtool[0].audio_silence_duration)"
			ffmpeg -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" -af "adelay=${silence_d}|${silence_d}" "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$param_title.$param_format" -y
		else
			if [ $(uci get ffmpegtool.@ffmpegtool[0].src_directory_path) = $(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path) ];then
				output_name=$(echo $i | cut -d '.' -f1)
			else
				output_name=${i%.*}
			fi
			ffmpeg $param_starttime $param_endtime -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $param_rate $param_channel $audios_param $param_title $param_copy "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/${output_name}.$param_format" -y
		fi
		echo "转换完成!" >> /tmp/ffmpeg.log
	done
elif [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "streaming media" ];then
	srctarget="$(uci get ffmpegtool.@ffmpegtool[0].src_stream_path)"
	ffprobe "$srctarget" > /tmp/ffmpeg.log 2>&1
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].dest_select)" == "Sound Card" ];then
		echo "$srctarget ---- 播放中..." >> /tmp/ffmpeg.log
		ffmpeg -i "$srctarget" $param_rate $param_channel $audios_param $param_copy -f alsa default
		echo "播放完毕!" >> /tmp/ffmpeg.log
	else
		echo "$srctarget ---- 导出中..." >> /tmp/ffmpeg.log
		ffmpeg -i "$srctarget" $param_rate $param_channel $audios_param $param_copy "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(date +%s).$param_format" -y
		echo "导出完毕!" >> /tmp/ffmpeg.log
	fi
elif [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "microphone" ];then
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].dest_select)" == "directory" ];then
		theoutput="$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/output-$(date +%s).$param_format"
		echo "麦克风录音： 保存到$theoutput... " >> /tmp/ffmpeg.log
		#arecord -D default -f cd -c 1 "$theoutput"
		ffmpeg -f alsa -i default $param_rate $param_channel $audios_param "$theoutput" -y
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].dest_select)" == "Sound Card" ];then
		echo "麦克风本地边录边放： 进行中... " >> /tmp/ffmpeg.log
		#arecord -D default -f cd -c 1 | aplay
		ffmpeg -f alsa -i default $param_rate $param_channel $audios_param -f alsa default
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].dest_select)" == "streaming media server" ];then
		echo "麦克风推流: 进行中... 目标：$(uci get ffmpegtool.@ffmpegtool[0].rtmp_server_url) " >> /tmp/ffmpeg.log
		if [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "rtmp server" ];then
			ffmpeg -f alsa -i default $param_rate $param_channel $audios_param $param_copy -f flv "$(uci get ffmpegtool.@ffmpegtool[0].rtmp_server_url)"
		elif [ "$(uci get ffmpegtool.@ffmpegtool[0].streamserver_select)" == "icecast server" ];then
			ffmpeg -f alsa -i default $param_rate $param_channel $audios_param $param_copy -f mp3 "$(uci get ffmpegtool.@ffmpegtool[0].icecast_server_url)"
		fi
	fi
fi

ucidefault

