#!/bin/sh
. /usr/ffmpegtool/commonfunc

testdestpath

param_format="$(uci get ffmpegtool.@ffmpegtool[0].audio_format)"
param_rate=""
param_channel=""
param_starttime=""
param_endtime=""
param_tone=""
param_speed=""
param_volume=""
param_title=""
param_copy=""

if [ "$(uci get ffmpegtool.@ffmpegtool[0].sampling_rate)" != "none" ];then
	param_rate="-ar $(uci get ffmpegtool.@ffmpegtool[0].sampling_rate)"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_channel)" != "none" ];then
	param_channel="-ac $(uci get ffmpegtool.@ffmpegtool[0].audio_channel)"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" != "none" ];then
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "sharp(44100Hz)" ];then
		param_tone="asetrate=44100*2^(1/12),atempo=1/2^(1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "sharp(22050Hz)" ];then
		param_tone="asetrate=22050*2^(1/12),atempo=1/2^(1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "rasing whole tone(44100Hz)" ];then
		param_tone="asetrate=44100*2^(2/12),atempo=1/2^(2/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "rasing whole tone(22050Hz)" ];then
		param_tone="asetrate=22050*2^(2/12),atempo=1/2^(1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "flat(44100Hz)" ];then
		param_tone="asetrate=44100*2^(-1/12),atempo=1/2^(-1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "flat(22050Hz)" ];then
		param_tone="asetrate=22050*2^(-1/12),atempo=1/2^(1/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "falling whole tone(44100Hz)" ];then
		param_tone="asetrate=44100*2^(-2/12),atempo=1/2^(-2/12),"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].risingfalling_tone)" == "falling whole tone(22050Hz)" ];then
		param_tone="asetrate=22050*2^(-2/12),atempo=1/2^(1/12),"
	fi
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].a_speed_governing)" != "none" ];then
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].a_speed_governing)" == "0.5" ];then
		param_speed="atempo=0.5,"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].a_speed_governing)" == "1.0" ];then
		param_speed="atempo=1.0,"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].a_speed_governing)" == "1.5" ];then
		param_speed="atempo=1.5,"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].a_speed_governing)" == "2.0" ];then
		param_speed="atempo=2.0,"
	fi
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" != "none" ];then
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "standard" ];then
		param_volume="loudnorm=i=-14:tp=0.0"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "+5dB" ];then
		param_volume="volume=5dB"
	elif [ "$(uci get ffmpegtool.@ffmpegtool[0].volume)" == "-5dB" ];then
		param_volume="volume=-5dB"
	fi
fi

if [ "$param_tone" == "" -a "$param_speed" == "" -a "$param_volume" == "" ];then
	audios_param="$param_tone$param_speed$param_volume"
else
	audios_param="$(echo $param_tone$param_speed$param_volume | sed 's/,$//')"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_copy)" == "1" ];then
	param_copy="-acodec copy"
fi

if [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "one file" ];then
	srctarget="$(uci get ffmpegtool.@ffmpegtool[0].src_file_path)"
	ffprobe "$srctarget" > /tmp/ffmpeg.log 2>&1
	time_work_a
	if [ ! -n "$(cat /tmp/ffmpeg.log | grep title)" -a "$(uci get ffmpegtool.@ffmpegtool[0].audio_addtitle)" == "1" ];then
		param_title="-metadata title=$(uci get ffmpegtool.@ffmpegtool[0].src_file_path | cut -d '/' -f$(expr $(uci get ffmpegtool.@ffmpegtool[0].src_file_path | grep -o / | wc -l) + 1) | cut -d '.' -f1)"
	fi
	echo "$srctarget ---- 转换中..." >> /tmp/ffmpeg.log
	if [ "$param_tone" == "" -a "$param_speed" == "" -a "$param_volume" == "" ];then
		if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_titleisname)" == "1" ];then
			param_title="$(cat /tmp/ffmpeg.log | grep title | awk '{print$3}')"
			ffmpeg $param_starttime $param_endtime -i "$srctarget" $param_rate $param_channel $audios_param $param_copy "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$param_title.$param_format" -y
		else
			ffmpeg $param_starttime $param_endtime -i "$srctarget" $param_rate $param_channel $audios_param $param_copy $param_title "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(uci get ffmpegtool.@ffmpegtool[0].src_file_path | cut -d '/' -f$(expr $(uci get ffmpegtool.@ffmpegtool[0].src_file_path | grep -o / | wc -l) + 1) | cut -d '.' -f1).$param_format" -y
		fi
	else
		if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_titleisname)" == "1" ];then
			param_title="$(cat /tmp/ffmpeg.log | grep title | awk '{print$3}')"
			ffmpeg $param_starttime $param_endtime -i "$srctarget" $param_rate $param_channel -filter_complex:a $audios_param "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$param_title.$param_format" -y
		else
			ffmpeg $param_starttime $param_endtime -i "$srctarget" $param_rate $param_channel -filter_complex:a $audios_param $param_title "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(uci get ffmpegtool.@ffmpegtool[0].src_file_path | cut -d '/' -f$(expr $(uci get ffmpegtool.@ffmpegtool[0].src_file_path | grep -o / | wc -l) + 1) | cut -d '.' -f1).$param_format" -y
		fi
	fi
	echo "转换完成!" >> /tmp/ffmpeg.log
elif [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "all files in the directory" ];then
	srctarget="$(ls $(uci get ffmpegtool.@ffmpegtool[0].src_directory_path))"
	for i in $srctarget;do
		ffprobe "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" > /tmp/ffmpeg.log 2>&1
		time_work_a
		if [ ! -n "$(cat /tmp/ffmpeg.log | grep title)" -a "$(uci get ffmpegtool.@ffmpegtool[0].audio_addtitle)" == "1" ];then
			param_title="-metadata title="$(echo "$i" | cut -d '.' -f1)""
		fi
		echo "$i ---- 转换中..." >> /tmp/ffmpeg.log
		if [ "$param_tone" == "" -a "$param_speed" == "" -a "$param_volume" == "" ];then
			if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_titleisname)" == "1" ];then
				ffmpeg $param_starttime $param_endtime -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $param_rate $param_channel $audios_param $param_copy "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$param_title.$param_format" -y
			else
				ffmpeg $param_starttime $param_endtime -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $param_rate $param_channel $param_title $audios_param $param_copy "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(echo $i | cut -d '.' -f1).$param_format" -y
			fi
		else
			if [ "$(uci get ffmpegtool.@ffmpegtool[0].audio_titleisname)" == "1" ];then
				param_title="$(cat /tmp/ffmpeg.log | grep title | awk '{print$3}')"
				ffmpeg $param_starttime $param_endtime -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $param_rate $param_channel -filter_complex:a $audios_param "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$param_title.$param_format" -y
			else
				ffmpeg $param_starttime $param_endtime -i "$(uci get ffmpegtool.@ffmpegtool[0].src_directory_path)/$i" $param_rate $param_channel -filter_complex:a $audios_param $param_title "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(echo $i | cut -d '.' -f1).$param_format" -y
			fi
		fi
		echo "转换完成!" >> /tmp/ffmpeg.log
	done
elif [ "$(uci get ffmpegtool.@ffmpegtool[0].src_select)" == "streaming media" ];then
	srctarget="$(uci get ffmpegtool.@ffmpegtool[0].src_stream_path)"
	ffprobe "$srctarget" > /tmp/ffmpeg.log 2>&1
	if [ "$(uci get ffmpegtool.@ffmpegtool[0].dest_select)" == "Sound Card" ];then
		echo "$srctarget ---- 播放中..." >> /tmp/ffmpeg.log
		if [ "$param_tone" == "" -a "$param_speed" == "" -a "$param_volume" == "" ];then
			ffmpeg -i "$srctarget" $param_rate $param_channel $audios_param -f alsa default
		else
			ffmpeg -i "$srctarget" $param_rate $param_channel -filter_complex:a $audios_param -f alsa default
		fi
		echo "播放完毕!" >> /tmp/ffmpeg.log
	else
		echo "$srctarget ---- 导出中..." >> /tmp/ffmpeg.log
		if [ "$param_tone" == "" -a "$param_speed" == "" -a "$param_volume" == "" ];then
			ffmpeg -i "$srctarget" $param_rate $param_channel $audios_param "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(date +%s).$param_format" -y
		else
			ffmpeg -i "$srctarget" $param_rate $param_channel -filter_complex:a $audios_param "$(uci get ffmpegtool.@ffmpegtool[0].dest_directory_path)/$(date +%s).$param_format" -y
		fi
		echo "导出完毕!" >> /tmp/ffmpeg.log
	fi
fi

ucidefault

