#!/bin/sh

basex=700
basey=290

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

while true
do
	rtime=$(echo `expr $(date +"%s" | cut -c 10) + 1`)
	rx=$(echo `expr $basex + $rtime`)
	ry=$(echo `expr $basey + $rtime`)
	adb -s ${adbclient}:5555 shell input swipe ${rx} ${ry} 385 226
	adb -s ${adbclient}:5555 shell input tap 65 950
	sleep 1
	adb -s ${adbclient}:5555 shell input tap ${rx} ${ry}
	adb -s ${adbclient}:5555 shell input swipe ${rx} ${ry} 385 226
done

