---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2018/6/20 16:45
---

module("luci.controller.admin.common", package.seeall)

function index()
    local wirelessnew = require "luci.controller.admin.wirelessnew"
    if (wirelessnew.wds_is_enabled() > 0) then
        entry({"admin", "common"}, template("new_siwifi/common_settings/common_settings")).leaf = true;
    else
        entry({"admin", "common"}, template("new_siwifi/common_settings/common_settings"), "",59).leaf = true;
    end
end
