---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2018/6/20 16:45
---

module("luci.controller.admin.guide", package.seeall)

function index()
    local uci = require "luci.model.uci"
    local _uci_real  = cursor or _uci_real or uci.cursor()
    local guide = _uci_real:get("basic_setting", "guide", "enable")
    if tonumber(guide) == 1 then
        entry({"admin", "guide"}, template("new_siwifi/common_settings/setting_guide"), "guide", 20).leaf = true;
    else
        entry({"admin", "guide"}, template("new_siwifi/common_settings/setting_guide")).leaf = true;
    end
end