#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

if [ $(cat /sys/devices/platform/leds-gpio/leds/hq65:red:system/brightness) = 1 ];then
	# tune off leds
	echo 0 > /sys/devices/platform/leds-gpio/leds/hq65:red:system/brightness
	echo 0 > /sys/devices/platform/leds-gpio/leds/hq65:green:wan/brightness
	echo 0 > /sys/devices/platform/leds-gpio/leds/hq65:green:wlan/brightness
	#fm_tea5767 /dev/i2c-0 87.5
    i2cset -y 0 0x3C 0x00 0xAE
else
	# tune on leds
	echo 1 > /sys/devices/platform/leds-gpio/leds/hq65:red:system/brightness
	echo 1 > /sys/devices/platform/leds-gpio/leds/hq65:green:wan/brightness
	echo 1 > /sys/devices/platform/leds-gpio/leds/hq65:green:wlan/brightness
	#fm_tea5767 /dev/i2c-0 103.7
    i2cset -y 0 0x3C 0x00 0xAF
fi

return 0
