#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

if [ $(cat /sys/devices/platform/leds-gpio/leds/hq65:red:system/brightness) = 1 ];then
	# tune off leds
	echo 0 > /sys/devices/platform/leds-gpio/leds/hq65:red:system/brightness
	echo 0 > /sys/devices/platform/leds-gpio/leds/hq65:green:wan/brightness
	echo 0 > /sys/devices/platform/leds-gpio/leds/hq65:green:wlan/brightness
else
	# tune on leds
	echo 1 > /sys/devices/platform/leds-gpio/leds/hq65:red:system/brightness
	echo 1 > /sys/devices/platform/leds-gpio/leds/hq65:green:wan/brightness
	echo 1 > /sys/devices/platform/leds-gpio/leds/hq65:green:wlan/brightness
fi

return 0
