#!/bin/sh

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

function look30sec() {
	sleep 8
	adb -s ${adbclient}:5555 shell input swipe 835 850 835 500
	sleep 8
	adb -s ${adbclient}:5555 shell input swipe 835 850 835 500
	sleep 8
	adb -s ${adbclient}:5555 shell input swipe 835 850 835 500
	sleep 8
}

adb connect ${adbclient}:5555
sleep 2

adb -s ${adbclient}:5555 shell am start -n com.taobao.live/.home.activity.TaoLiveHomeActivity
sleep 5

adb -s ${adbclient}:5555 shell input tap 950 1845
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 1845
sleep 3

adb -s ${adbclient}:5555 shell input tap 535 1325
sleep 3
adb -s ${adbclient}:5555 shell input tap 535 1080
sleep 3
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 950 700
sleep 3

adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3

adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3
adb -s ${adbclient}:5555 shell input tap 950 200
sleep 3

adb -s ${adbclient}:5555 shell input tap 780 1280
sleep 5

adb -s ${adbclient}:5555 shell input tap 155 1425
sleep 3

adb -s ${adbclient}:5555 shell input tap 858 1368
sleep 3
adb -s ${adbclient}:5555 shell input tap 885 510
sleep 3

adb -s ${adbclient}:5555 shell input tap 858 1368
sleep 5

adb -s ${adbclient}:5555 shell input tap 220 990
sleep 3

adb -s ${adbclient}:5555 shell input tap 550 1780
sleep 5

adb -s ${adbclient}:5555 shell input tap 385 1460
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 860
sleep 12

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 5
adb -s ${adbclient}:5555 shell input tap 910 860
sleep 12

adb -s ${adbclient}:5555 shell input tap 550 1800
sleep 3

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 5

ltimes=0
while [ $ltimes -lt 3 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 860
	sleep 3
	look30sec
	sleep 2
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done

ltimes=0
while [ $ltimes -lt 3 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 860
	sleep 3
	look30sec
	sleep 2
	look30sec
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done

ltimes=0
while [ $ltimes -lt 5 ]
do
	adb -s ${adbclient}:5555 shell input tap 910 860
	sleep 3
	look30sec
	sleep 2
	look30sec
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 3
	ltimes=$(echo `expr $ltimes + 1`)
done


adb -s ${adbclient}:5555 shell input tap 910 860
sleep 3
ltimes=0
while [ $ltimes -lt 7 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 860
sleep 3
ltimes=0
while [ $ltimes -lt 11 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 860
sleep 3
dianzan=0
while [ $dianzan -lt 22 ]
do
	adb -s ${adbclient}:5555 shell input tap 1000 1825
	sleep 1
	dianzan=$(echo `expr $dianzan + 1`)
done
sleep 1
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 860
sleep 5
adb -s ${adbclient}:5555 shell input tap 770 1760
sleep 7

adb -s ${adbclient}:5555 shell input tap 530 1315
sleep

adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 860
sleep 3
ltimes=0
while [ $ltimes -lt 17 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 860
sleep 3
ltimes=0
while [ $ltimes -lt 21 ]
do
	look30sec
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 910 860
sleep 1
ltimes=0
while [ $ltimes -lt 7 ]
do
	adb -s ${adbclient}:5555 shell input swipe 535 1300 535 900
	sleep 5
	ltimes=$(echo `expr $ltimes + 1`)
done
sleep 2
adb -s ${adbclient}:5555 shell input keyevent 4
sleep 3

adb -s ${adbclient}:5555 shell input tap 155 1425
sleep 2

adb -s ${adbclient}:5555 shell input tap 858 1368
sleep 3
adb -s ${adbclient}:5555 shell input tap 885 510
sleep 3

adb -s ${adbclient}:5555 shell input tap 858 1368
sleep 5

adb -s ${adbclient}:5555 shell input tap 550 990
sleep 3

adb -s ${adbclient}:5555 shell input tap 550 1780
sleep 5

adb -s ${adbclient}:5555 shell input tap 635 1645

