#!/bin/sh /etc/rc.common

START=99

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
	if [ ! -s /mnt/mmcblk0p1/caddy1/caddy7621.tar ];then
		cd /mnt/mmcblk0p1/caddy1
		wget-ssl -t 5 -w 3 -T 60 -c https://github.com/syb999/openwrt-caddy/raw/master/uclibc-ipk/caddy7621.tar
	fi
	cd /mnt/mmcblk0p1/caddy1
	tar -xvf caddy7621.tar -C /tmp
	service_start /tmp/caddy -conf /etc/caddy/Caddyfile
}

stop() {
	if [ -s /tmp/caddy ];then
		service_stop /tmp/caddy
	fi
}
