#!/bin/sh
. /usr/adbrun/worklist
#自行进入双11元宝狂欢节页面-进入幸运大抽奖页面

dosedxstart=
dosedystart=
dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1 | sed 's/^ADBRUN//')
adbclient=$(uci get adbrun.$sectionname.adbiplist)
rm /tmp/adb_ADBRUN${sectionname}_.sh

adb disconnect ${adbclient}:5555
sleep 2
adb connect ${adbclient}:5555
sleep 2

worklist=$(uci get adbrun.@adbinit[0].diantaoluckyworklistd11)
botting

rm /tmp/worklist${sectionname}.adbtmp
