#!/bin/sh
#自行进入淘宝双11喵糖总动员-点击赢红包页面

dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1 | sed 's/^ADBRUN//')
adbclient=$(uci get adbrun.$sectionname.adbiplist)
rm /tmp/adb_ADBRUN${sectionname}_.sh

adb disconnect ${adbclient}:5555
sleep 2
adb connect ${adbclient}:5555
sleep 2

while true
do
	adb -s ${adbclient}:5555 shell input tap $basex $basey
	sleep 3
done
