#!/bin/sh
. /usr/share/gmediarender/gmrloadfunc

while true
do
	gmr_init
	todolist="iqiyi qq.com bilivideo youku bdxiguavod hifuntv.com xiaoniangao music upgcxcode gtimg.com baidu.com"
	for t in $todolist;do
		gotod=$t
		if [ ! -z "$(cat /tmp/xgmrender.tmp.find | grep $t)" ];then
			if [ $t == "upgcxcode" ];then
				gotod="bilivideo"
			elif [ $t == "gtimg.com" ];then
				gotod="qq.com"
			fi
			break
		fi
	done
	/usr/share/gmediarender/gmrdownload $gotod &
	sleep 3
done

