#!/bin/sh
gmrlog="/tmp/$(uci get gmediarender.@gmediarender[0].gmrenderlog)"
kill $(ps | grep gmrdownload | grep -v grep | grep -v gmrdownloadstop | head -n 1 | cut -d 'r' -f 1)
rm /tmp/xgmrender.tmp.*
echo "clear" > $gmrlog
