#!/bin/sh

gmrdir="$(uci get gmediarender.@gmediarender[0].gmrenderdir)"
gmrlog="/tmp/$(uci get gmediarender.@gmediarender[0].gmrenderlog)"
saferom="$(df -h | grep tmpfs | sed -e "s/[ ][ ]* / /g" | head -n 1 | cut -d ' ' -f 5 | cut -d '%' -f 1)"

wget-ssl -q -c $(uci get network.lan.ipaddr) -O /tmp/xgmrender.tmp.testwget > /dev/null 2>&1
if [ -s /tmp/xgmrender.tmp.testwget ];then
	wget=wget-ssl
else
	wget=wget
fi

if [ ! -d "$gmrdir" ];then
	mkdir -p $gmrdir
fi

function gmr_init(){
	cd $gmrdir
	if [ ! -s $gmrlog ];then
		/etc/init.d/gmediarender restart
	fi
	cat $gmrlog | grep -n "CurrentTrackURI: http" | head -n 1 > /tmp/xgmrender.tmp.find
	findurl=$(cat /tmp/xgmrender.tmp.find)
	while [ ! -n "$findurl" ]
	do
		sleep 3
		cat $gmrlog | grep -n "CurrentTrackURI: http" | head -n 1 > /tmp/xgmrender.tmp.find
		findurl=$(cat /tmp/xgmrender.tmp.find)
	done
	theurl=$(echo ${findurl#*CurrentTrackURI: } > /tmp/xgmrender.tmp.urlx)
	if [ -n $(cat $geturl) ];then
		theurl=$(echo ${findurl#*CurrentTrackURI val=} > /tmp/xgmrender.tmp.urlx)
	fi
	cat /tmp/xgmrender.tmp.urlx | sed 's/^.*http:/http:/' > /tmp/xgmrender.tmp.url
	geturl=$(cat /tmp/xgmrender.tmp.url)
}

function gmr_musicinit(){
	thedirname="music"
	ismp3=$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '.' -f 2 | cut -d '?' -f 1)
	if [ $ismp3 == "mp3" ];then
		urlsuffix="mp3"
		thename="$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '.' -f 1 | sed 's/?/？/g').$urlsuffix"
	else
		urlsuffix="m4a"
		thename="$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '.' -f 1 | sed 's/?/？/g').$urlsuffix"
	fi
	if [ "$(echo $thename | wc -c)" -gt 80 ];then
		thename="$(echo $thename  | sed 's/^mp3.*-//;s/\.mp3$/\.m4a/')"
	fi
	findurl2="$(expr $(cat $gmrlog | grep -n "CurrentTrackURI: http" | head -n 1 | cut -d ':' -f 1) + 1)"
	informaudio="$(grep -n $findurl2 $gmrlog)"
	gettitle0="$(echo ${informaudio#*&lt;dc:title&gt;})"
	thetitle="$(echo ${gettitle0%%&lt;/dc:title&gt;*} | tr -d "a-zA-Z0-9~!@#$%^&*()_=+-\\\/[]{};\':\",.|-" | sed "s/[ ][ ]*//g")"
	getartist0="$(echo ${informaudio#*&lt;upnp:artist role=&quot;Performer&quot;&gt;})"
	theartist="$(echo ${getartist0%%&lt;/upnp:artist&gt;*} | tr -d "a-zA-Z0-9~!@#$%^&*()_=+-\\\/[]{};\':\",.|-" | sed "s/[ ][ ]*//g")"
	theaudio="${thetitle} ${theartist}"
}

function gmr_avqqinit(){
	if [ -n "$(echo $geturl | grep music.tc)" ];then
		thedirname="qqmusic"
		thename="$(cat $gmrlog | grep "<dc:title>" | head -n 1 | tr -d '<:>/dctile' | sed 's/^[ ][ ]*//g' | cut -d '=' -f8 | cut -d '"' -f 2 | sed 's/^[ ][ ]*//g;s/ /-/g')"
		if [ -n $(cat $thename) ];then
			thename="$(date +%s).mp3"
		fi
	elif [ -n "$(echo $geturl | grep qqmusic)" ];then
		thedirname="qqmusic"
		thename="$(cat $gmrlog | grep "<dc:title>" | head -n 1 | tr -d '<:>/dctile' | sed 's/^[ ][ ]*//g' | cut -d '=' -f8 | cut -d '"' -f 2 | sed 's/^[ ][ ]*//g;s/ /-/g')"
		if [ -n $(cat $thename) ];then
			thename="$(date +%s).mp3"
		fi
	else
		thedirname=$(cat $gmrlog | grep "<dc:title>" | head -n 1 | tr -d '<:>/dctile' | sed 's/^[ ][ ]*//g' | cut -d ' ' -f 1)
		them3u8=$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '?' -f 1)
		thesuffix=$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1))
		thename=$(cat $gmrlog | grep "<dc:title>" | head -n 1 | tr -d '<:>/dctile' | sed 's/^[ ][ ]*//g;s/ /-/g')
	fi
}

function gmr_bilibiliinit(){
	thedirname="bilibili"
	thevfile=$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '?' -f 1)
	thesuffix=$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '?' -f 1 | cut -d '.' -f 2)
	findurl2="$(cat $gmrlog | grep "<dc:title>" | head -n 1)"
	getname0="$(echo ${findurl2#*<dc:title>})"
	thenamea="$(echo ${getname0%%</dc:title>*} | sed 's/[ ][ ]*//g' | sed "s/第[0-9]话/&#*#/" | tr -cd '0-9\n#*#' | grep "#*#" | tr -d '#*#' | sed 's/^/第0/;s/$/话/')"
	thenameb="$(echo ${getname0%%</dc:title>*} | sed 's/[ ][ ]*//g' | cut -d '-' -f 2 )"
	if [ ! -n "$thenamea" ];then
		thename="$(echo ${getname0%%</dc:title>*} | sed 's/[ ][ ]*//g')"
	else
		thename="${thenamea}-${thenameb}"
	fi
}

function gmr_xiguainit(){
	thedirname="xigua"
	thename="$(date +%m%d)"
}

function gmr_iqiyiinit(){
	thedirname="iqiyi"
	them3u8=$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '?' -f 1)
	thename="$(cat /tmp/gmrender.tmp.log | grep "item id=" | sed 's/item id=\"/\n/' | sed '1d' | head -n1 | cut -d '"' -f1)"
	if [ "$thename" = "" ];then
		thename="$(date +%H-%M)"
	else
		thedirname="$(echo "$thename" | sed 's/\ /-/g;s/第[0-9]*集//;s/-$//')"
	fi
}

function gmr_youkuinit(){
	thedirname="youku"
	them3u8=$(cat /tmp/xgmrender.tmp.url | cut -d '/' -f $(expr $(grep -o '/' /tmp/xgmrender.tmp.url | wc -l) + 1) | cut -d '?' -f 1)
	findurl2="$(cat $gmrlog | grep "<dc:title>" | head -n 1)"
	getname0="$(echo ${findurl2#*<dc:title>})"
	thename="$(echo ${getname0%%</dc:title>*} | sed 's/[ ][ ]*//g')"
}

function gmr_mangotvinit(){
	thedirname="mangotv"
	findurlinfo=$(cat $gmrlog | grep ".ts" | grep http | tail -n1 | sed 's/&gt;/\n/g')
	thetitle="$(cat $gmrlog | grep ".ts" | grep http | tail -n1 | sed 's/&gt;/\n/g' | grep "$lt;/dc:title" | sed 's/\&lt;\/dc:title//;s/ /-/g')"
	findnum=$(echo $thetitle | sed 's/第/\n/g;s/集/\n/g' | tail -n2 | head -n1)
	if [ $findnum -lt 10 ];then
		thetitle=$(echo $thetitle | sed "s/第$findnum集/第00$findnum集/")
	elif [ $findnum -lt 100 ];then
		thetitle=$(echo $thetitle | sed "s/第$findnum集/第0$findnum集/")
	fi
	#theurl="$(echo $findurlinfo | grep http | tail -n1 | sed 's/\&amp;/\n/g' | head -n1)"
}

function gmr_xiaoniangaoinit(){
	thedirname="小年糕"
	thename="$(date +%m%d)"
	echo ${geturl#*CurrentTrackURI: } > /tmp/xgmrender.tmp.url
	geturl=$(cat /tmp/xgmrender.tmp.url)
}

function gmr_baidunetdiskinit(){
	thedirname="BaiduNetdisk"
	thename="$(date +%m%d)"
	echo ${geturl#*CurrentTrackURI: } > /tmp/xgmrender.tmp.url
	geturl=$(cat /tmp/xgmrender.tmp.url)
}

function gmr_dirinit(){
	if [ ! -d "$gmrdir/$thedirname" ]; then
		mkdir -p "$gmrdir/$thedirname"
		chmod 777 -R "$gmrdir/$thedirname"
	fi
}

function gmr_musicdownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		$wget --timeout=3 -q $geturl -O $gmrdir/$thedirname/"$thename"
	fi
}

function gmr_avqqdownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		if [ -n "$(echo $geturl | grep music.tc)" ];then
			if [ ! -n $(echo $geturl | cut -d ' ' -f7);then
				$wget --timeout=3 -q $geturl -O $gmrdir/$thedirname/"$thename"	
			else
				geturl=$(echo $geturl | cut -d ' ' -f7)
				$wget --timeout=3 -q $geturl -O $gmrdir/$thedirname/"$thename"	
			fi
		elif [ -n "$(echo $geturl | grep qqmusic)" ];then
			if [ ! -n $(echo $geturl | cut -d ' ' -f7);then
				$wget --timeout=3 -q $geturl -O $gmrdir/$thedirname/"$thename"	
			else
				geturl=$(echo $geturl | cut -d ' ' -f7)
				$wget --timeout=3 -q $geturl -O $gmrdir/$thedirname/"$thename"	
			fi
		else
			rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
			if [ ! -z $(cat /tmp/xgmrender.tmp.m3u8) ];then
				$wget --timeout=10 -q -c "${geturl}" -O "${them3u8}"
				isbin=$(file /tmp/xgmrender.tmp.m3u8)
				if [ "$isbin" == "/tmp/xgmrender.tmp.m3u8: data" ];then
					echo skip
				else
					if [ ! -n "$(echo $them3u8 | grep m3u8)" ];then
						echo get mp4
					else
						cat $them3u8 | grep .ts > /tmp/xgmrender.tmp.m3u8$rdsuffix
						tmpm3u8=$(cat /tmp/xgmrender.tmp.m3u8$rdsuffix)
						theprefix=$(cat /tmp/xgmrender.tmp.url | sed "s/${thesuffix}//")
						for i in $tmpm3u8
						do
							tsfragment="${theprefix}${i}"
							$wget --timeout=3 -q $tsfragment -O /tmp/xgmrender.tmp.fragment$rdsuffix
							cat /tmp/xgmrender.tmp.fragment$rdsuffix >> $gmrdir/$thename.ts.downloading$rdsuffix
						done
					fi
				fi
				if [ -s $thename.ts.downloading$rdsuffix ];then
					mv $gmrdir/$thename.ts.downloading$rdsuffix "$gmrdir/$thedirname/$thename.ts"
				else
					mv "$gmrdir/$them3u8 $gmrdir/$thedirname/$thename.mp4"
					rm "$gmrdir/$thename.ts.downloading$rdsuffix"
				fi
				rm /tmp/xgmrender.tmp.m3u8$rdsuffix /tmp/xgmrender.tmp.fragment$rdsuffix $them3u8
			else
				geturl="$(echo $geturl | awk '{print$7}')"
				if [ ! -z "$(echo $geturl | awk '{print $7}')" ]; then
					thedirname="wechat_video"
					gmr_dirinit
					$wget --timeout=10 -q -c $geturl -O "$gmrdir/$thedirname/$rdsuffix.mp4"
				else
					$wget --timeout=10 -q -c "$(cat /tmp/xgmrender.tmp.url)" -O "${them3u8}"
					if [ ! -n "$(echo $them3u8 | grep m3u8)" ];then
						echo get mp4
					else
						cat $them3u8 | grep .ts > /tmp/xgmrender.tmp.m3u8$rdsuffix
						tmpm3u8=$(cat /tmp/xgmrender.tmp.m3u8$rdsuffix)
						theprefix=$(cat /tmp/xgmrender.tmp.url | sed "s/${thesuffix}//")
						for i in $tmpm3u8;do
							tsfragment="${theprefix}${i}"
							$wget --timeout=3 -q $tsfragment -O /tmp/xgmrender.tmp.fragment$rdsuffix
							cat /tmp/xgmrender.tmp.fragment$rdsuffix >> $gmrdir/$thename.ts.downloading$rdsuffix
						done
					fi
					if [ -s $thename.ts.downloading$rdsuffix ];then
						mv $gmrdir/$thename.ts.downloading$rdsuffix "$gmrdir/$thedirname/$thename.ts"
					else
						mv "$gmrdir/$them3u8 $gmrdir/$thedirname/$thename.mp4"
						rm "$gmrdir/$thename.ts.downloading$rdsuffix"
					fi
				fi
				rm /tmp/xgmrender.tmp.m3u8$rdsuffix /tmp/xgmrender.tmp.fragment$rdsuffix $them3u8
			fi
		fi
	fi
}

function gmr_bilibilidownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
		$wget --timeout=3 -q "$geturl" -O "$gmrdir/$thename.downloading$rdsuffix"
		mv "$gmrdir/$thename.downloading$rdsuffix" "$gmrdir/$thedirname/$thename.$thesuffix"
	fi
}

function gmr_xiguadownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
		$wget --timeout=3 -q "$geturl" -O "$gmrdir/$thedirname/$thename.mp4.fragment$rdsuffix"
		mv "$gmrdir/$thedirname/$thename.mp4.fragment$rdsuffix" "$gmrdir/$thedirname/$thename-$(date +%s).mp4"
	fi
}

function gmr_iqiyidownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
		isbin=$(file /tmp/xgmrender.tmp.m3u8)
		if [ "$isbin" == "/tmp/xgmrender.tmp.m3u8: data" ];then
			echo skip
		else
			$wget --timeout=10 -q -c $geturl -O $them3u8
			cat $them3u8 | grep .ts > /tmp/xgmrender.tmp.m3u8$rdsuffix
			tmpm3u8=$(cat /tmp/xgmrender.tmp.m3u8$rdsuffix)
			for i in $tmpm3u8
			do
				$wget --timeout=3 -q $i -O /tmp/xgmrender.tmp.fragment$rdsuffix
				cat /tmp/xgmrender.tmp.fragment$rdsuffix >> "$gmrdir/$thename.ts.downloading$rdsuffix"
			done
		fi
		if [ -s "$thename.ts.downloading$rdsuffix" ];then
			mv "$gmrdir/$thename.ts.downloading$rdsuffix" "$gmrdir/$thedirname/$(echo $thename | sed 's/ //g').ts"
		else
			mv "$gmrdir/$them3u8" "$gmrdir/$thedirname/$(echo $thename | sed 's/ //g')-$(date +%s).mp4"
			rm "$gmrdir/$thename.ts.downloading$rdsuffix"
		fi
		rm /tmp/xgmrender.tmp.m3u8$rdsuffix /tmp/xgmrender.tmp.fragment$rdsuffix $them3u8
	fi
}

function gmr_youkudownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
		$wget --timeout=10 -q $geturl -O /tmp/xgmrender.tmp.mtmp
		cat /tmp/xgmrender.tmp.mtmp | grep .ts | sed 's/\r$//' | cut -d ' ' -f 1 > /tmp/xgmrender.tmp.m3u8$rdsuffix
		tmpm3u8=$(cat /tmp/xgmrender.tmp.m3u8$rdsuffix)
		for i in $tmpm3u8
		do
			$wget --timeout=3 -q $i -O /tmp/xgmrender.tmp.fragment$rdsuffix
			cat /tmp/xgmrender.tmp.fragment$rdsuffix >> $gmrdir/$thename.ts.downloading$rdsuffix
		done
		if [ -s $thename.ts.downloading$rdsuffix ];then
			mv $gmrdir/$thename.ts.downloading$rdsuffix $gmrdir/$thedirname/$thename.ts
		else
			mv $gmrdir/$them3u8 $gmrdir/$thedirname/$thename.mp4
			rm $gmrdir/$thename.ts.downloading$rdsuffix
		fi
		rm /tmp/xgmrender.tmp.m3u8$rdsuffix /tmp/xgmrender.tmp.fragment$rdsuffix /tmp/xgmrender.tmp.mtmp
	fi
}

function gmr_mangotvdownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
		$wget --timeout=3 -q $geturl -O $gmrdir/$thetitle.downloading$rdsuffix
		mv $gmrdir/$thetitle.downloading$rdsuffix $gmrdir/$thedirname/$thetitle.ts
	fi
}

function gmr_xiaoniangaodownload(){
       if [ $saferom -gt 80 ];then
               logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
       else
               rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
               $wget --timeout=3 -q $geturl -O $gmrdir/$thedirname/$thename.mp4.fragment$rdsuffix
               mv $gmrdir/$thedirname/$thename.mp4.fragment$rdsuffix $gmrdir/$thedirname/$thename-$(date +%s).mp4
       fi
}

function gmr_baidunetdiskdownload(){
	if [ $saferom -gt 80 ];then
		logger -t gmediarender ☆☆☆☆☆☆☆ Not enough diskspace! ☆☆☆☆☆☆☆
	else
		rdsuffix=$(head -n 1 /dev/urandom | tr -dc "0-9a-z" | head -c8)
		$wget --timeout=10 -q $geturl -O /tmp/xgmrender.tmp.mtmp
		cat /tmp/xgmrender.tmp.mtmp | grep https | cut -d '/' -f5- > /tmp/xgmrender.tmp.m3u8$rdsuffix
		theprefix="https://yqct06.baidupcs.com/video/"
		tmpm3u8=$(cat /tmp/xgmrender.tmp.m3u8$rdsuffix)
		for i in $tmpm3u8
		do
			$wget --timeout=3 -q $theprefix$i -O /tmp/xgmrender.tmp.fragment$rdsuffix
			cat /tmp/xgmrender.tmp.fragment$rdsuffix >> $gmrdir/$thename.ts.downloading$rdsuffix
		done
		mv $gmrdir/$thename.ts.downloading$rdsuffix $gmrdir/$thedirname/$thename.$rdsuffix.ts
		rm /tmp/xgmrender.tmp.m3u8$rdsuffix /tmp/xgmrender.tmp.fragment$rdsuffix /tmp/xgmrender.tmp.mtmp
	fi
}

function gmr_clear(){
	rm /tmp/xgmrender.tmp.* $gmrdir/$them3u8 $gmrdir/$thename.ts
	echo "clear" > $gmrlog
}
