# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for ap customed by siflower
LUCI_DEPENDS:=+siflower-ap

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
