#!/bin/sh

HI=/proc/hi

check_ip()
{
	echo $1|grep "^[0-9]\{1,3\}\.\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}$" > /dev/null;
	if [ $? -ne 0 ]; then
		echo "error ip address"
		exit
	fi
	ipaddr=$1
	a=`echo $ipaddr|awk -F . '{print $1}'`
	b=`echo $ipaddr|awk -F . '{print $2}'`
	c=`echo $ipaddr|awk -F . '{print $3}'`
	d=`echo $ipaddr|awk -F . '{print $4}'`
	for num in $a $b $c $d
	do
		if [ $num -gt 255 ] || [ $num -lt 0 ]; then
			echo "error ip address"
			exit
		fi
	done
	return 0
}

add_cmd(){
	local mac=$(echo $2 | grep -E ^\([0-9a-fA-F]{2}:\){5}[0-9a-fA-F]{2}\$)
	local sip=$3
	local dip=$4
	local sport=$5
	local dport=$6
	local qos_en
	local qos

	if [ "x$8" = "x" ];then
	   	qos_en=0
	else
		if [ $8 -eq 1 -o $8 -eq 0 ];then
			qos_en=$8
		else
			echo "qos_en param error"
			exit
		fi
	fi
	if [ "x$9" = "x" ];then
	   	qos=0
	else
		if [ $9 -ge 0 ];then
			qos=$9
		else
			echo "qos param error"
			exit
		fi
	fi

	if [ "x$7" = "xaccept" ];then
		local action=1
	elif [ "x$7" = "xdrop" ];then
		local action=0
	else
		echo "action error"
	fi

	if [ "x$mac" = "x" ]; then
		echo "error mac address"
		exit
	fi
	check_ip $sip
	check_ip $dip
	if [ $sport -lt 0 -o $sport -ge 65535 ]; then
		echo "error port"
		exit
	fi

	if [ $dport -lt 0 -o $dport -ge 65535 ]; then
		echo "error port"
		exit
	fi

	printf "$1 $mac $sip $dip $sport $dport $action $qos_en $qos" > $HI
}

del_cmd(){
	printf "$1 $2" > $HI
}

edit_cmd(){
	local mac=$(echo $2 | grep -E ^\([0-9a-fA-F]{2}:\){5}[0-9a-fA-F]{2}\$)
	local sip=$3
	local dip=$4
	local sport=$5
	local dport=$6
	if [ "x$7" = "xaccept" ];then
		local action=1
	elif [ "x$7" = "xdrop" ];then
		local action=0
	else
		echo "action error"
	fi

	if [ "x$mac" = "x" ]; then
		echo "error mac address"
		exit
	fi
	check_ip $sip
	check_ip $dip
	if [ $sport -lt 0 -o $sport -ge 65535 ]; then
		echo "error port"
		exit
	fi

	if [ $dport -lt 0 -o $dport -ge 65535 ]; then
		echo "error port"
		exit
	fi

	printf "2 $1 $mac $sip $dip $sport $dport $action" > $HI
}

server_cmd(){
	local ip=$1
	local port=$2

	check_ip $ip
	if [ $port -lt 0 -o $port -ge 65535 ]; then
		echo "error port"
		exit
	fi

	printf "3 $ip $port" > $HI
}

client_cmd(){
	local cmd

	if [ "x$1" = "xstart" ];then
		cmd=1
	elif [ "x$1" = "xstop" ];then
		cmd=0
	else
		echo "client cmd error"
	fi

	printf "4 $cmd" > $HI
}

qos_cmd(){
	local qos_en
	local qos
	local num=$1

	if [ $2 -eq 1 -o $2 -eq 0 -o $2 -eq -1 ];then
		qos_en=$2
	else
		echo "qos_en param error"
		exit
	fi
	if [ $3 -gt -2 ];then
		qos=$3
	else
		echo "qos_en param error"
		exit
	fi
	printf "5 $num $qos_en $qos" > $HI
}

case $1 in
	add)
		shift;
		add_cmd 0 $@
		;;
	del)
		del_cmd 1 $2
		;;
	edit)
		shift;
		edit_cmd $@
		;;
	server)
		shift;
		server_cmd $@
		;;
	client)
		shift;
		client_cmd $@
		;;
	qos)
		shift;
		qos_cmd $@
		;;
	*)
		echo "error cmd"
		;;
esac
