#!/bin/sh
#自行进入双11元宝狂欢节页面并点击赚元宝升级-白天+晚上

dosedxstart=
dosedystart=
dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

function look30sec() {
	sleep 8
	for i in $(seq 1 3) ;do
		adb -s ${adbclient}:5555 shell input swipe $xstart $ystart $xstart $(echo `expr $ystart - 390`)
		sleep 9
	done
}

function botting() {
	echo $worklist | sed "s/ /\n/g" > /tmp/worklist${sectionname}.adbtmp
	workline=/tmp/worklist${sectionname}.adbtmp
	while read LINE
	do
		result=$(echo $LINE | grep "秒")
		if [ "$result" != "" ];then
			adbtimes=$(echo $LINE | sed "s/秒/\n/;s/次//" | tail -n 1)
			switchtimes=$(echo $LINE | sed "s/秒/\n/" | head -n 1)
			switchtimes=$(echo `expr $switchtimes \* 1`)
			adbswitchtimes=$(echo `expr $switchtimes / 30`)
			ltimes=0
			while [ $ltimes -lt ${adbtimes} ]
			do
				adb -s ${adbclient}:5555 shell input tap $basex $basey
				sleep 3
				for i in $(seq 1 ${adbswitchtimes}) ;do
					look30sec
				done
				sleep 2
				adb -s ${adbclient}:5555 shell input keyevent 4
				sleep 6
				ltimes=$(echo `expr $ltimes + 1`)
			done
		else
			adbtimes=$(echo $LINE | sed "s/分钟/\n/;s/次//" | tail -n 1)
			switchtimes=$(echo $LINE | sed "s/分钟/\n/" | head -n 1)
			switchtimes=$(echo `expr $switchtimes \* 60`)
			adbswitchtimes=$(echo `expr $switchtimes / 30`)
			ltimes=0
			while [ $ltimes -lt ${adbtimes} ]
			do
				adb -s ${adbclient}:5555 shell input tap $basex $basey
				sleep 3
				for i in $(seq 1 ${adbswitchtimes}) ;do
					look30sec
				done
				sleep 2
				adb -s ${adbclient}:5555 shell input keyevent 4
				sleep 6
				ltimes=$(echo `expr $ltimes + 1`)
			done
		fi
	done < $workline
}

adb disconnect ${adbclient}:5555
sleep 2
adb connect ${adbclient}:5555
sleep 2

gettimenow=$(date "+%H")

if [ $gettimenow -lt 20 -a $gettimenow -gt 7 ];then
	worklist=$(uci get adbrun.@adbinit[0].diantaodayworklist)
	botting
elif [ $gettimenow -le 7 -a $gettimenow -gt 1 ];then
	worklist=$(uci get adbrun.@adbinit[0].diantaodawnworklist)
	botting
else
	worklist=$(uci get adbrun.@adbinit[0].diantaonightworklist)
	botting
fi
rm /tmp/worklist${sectionname}.adbtmp
