#!/bin/sh
#自行进入淘宝一起赢20亿红包-做任务赚喵糖

dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

adb disconnect ${adbclient}:5555
sleep 2
adb connect ${adbclient}:5555
sleep 2

ltimes=0
while [ $ltimes -lt 20 ]
do
	adb -s ${adbclient}:5555 shell input tap $basex $basey
	sleep 30
	adb -s ${adbclient}:5555 shell input keyevent 4
	sleep 6
	ltimes=$(echo `expr $ltimes + 1`)
done
