#!/bin/sh

dosedbasex=
dosedbasey=
dosedbasecx=
dosedbasecy=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1 | sed 's/^ADBRUN//')
adbclient=$(uci get adbrun.$sectionname.adbiplist)
rm /tmp/adb_ADBRUN${sectionname}_.sh

adb connect ${adbclient}:5555

while true
do
	rtime=$(echo `expr $(date +"%s" | cut -c 10) + 1`)
	rx=$(echo `expr $basex + $rtime`)
	ry=$(echo `expr $basey + $rtime`)
	sleep $(echo `expr $rtime + 20`)
	adb -s ${adbclient}:5555 shell input tap $basecx $basecy
	sleep $(echo `expr $rtime + 10`)
	adb -s ${adbclient}:5555 shell input swipe ${rx} ${ry} $(echo `expr ${rx} + 10`) $(echo `expr ${ry} - 390`)
	adb -s ${adbclient}:5555 shell input tap $basecx $basecy
	sleep $(echo `expr $rtime + 30`)
done

