#!/bin/sh
. /usr/adbrun/worklist
#自行进入元宝中心-打工赚元宝-赚体力页面

dosedxstart=
dosedystart=
dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

adb disconnect ${adbclient}:5555
sleep 2
adb connect ${adbclient}:5555
sleep 2

gettimenow=$(date "+%H")

if [ $gettimenow -lt 20 -a $gettimenow -ge 0 ];then
	worklist=$(uci get adbrun.@adbinit[0].diantaodayworklist)
	botting
else
	worklist=$(uci get adbrun.@adbinit[0].diantaonightworklist)
	botting
fi
rm /tmp/worklist${sectionname}.adbtmp
