#!/bin/sh
. /usr/adbrun/worklist
#自行进入元宝中心-打工赚元宝-赚体力页面
starttime=
dosedxstart=
dosedystart=
dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1 | sed 's/^ADBRUN//')
adbclient=$(uci get adbrun.$sectionname.adbiplist)
rm /tmp/adb_ADBRUN${sectionname}_.sh

gettimenow=$(date +%H)

if [ $gettimenow -lt 20 -a $gettimenow -ge 0 ];then
	worklist=$(uci get adbrun.@adbinit[0].diantaodayworklist)
	botting
else
	worklist=$(uci get adbrun.@adbinit[0].diantaonightworklist)
	botting
fi
rm /tmp/worklist${sectionname}.adbtmp
