#!/bin/sh

dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

while true
do
	rtime=$(echo `expr $(date +"%s" | cut -c 10) + 1`)
	rx=$(echo `expr $basex + $rtime`)
	ry=$(echo `expr $basey + $rtime`)
	adb -s ${adbclient}:5555 shell input swipe ${rx} ${ry} $(echo `expr ${rx} + 10`) $(echo `expr ${ry} - 300`)
    sleep $(echo `expr $rtime + 15`)
done

