#!/bin/sh
starttime=
dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1 | sed 's/^ADBRUN//')
adbclient=$(uci get adbrun.$sectionname.adbiplist)
rm /tmp/adb_ADBRUN${sectionname}_.sh

while true
do
	rtime=$(expr $(date +%s | cut -c 10) + 1)
	rx=$(expr $basex + $rtime)
	ry=$(expr $basey + $rtime)
	adb -s ${adbclient}:5555 shell input swipe ${rx} ${ry} $(expr ${rx} - 300) ${ry}
	sleep 5
done

