#!/bin/sh

dosedbasex=
dosedbasey=

sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1)
adbclient=$(uci get adbrun.$sectionname.adbiplist)

adb disconnect ${adbclient}:5555
sleep 2
adb connect ${adbclient}:5555
sleep 2

while true
do
	rtime=$(echo `expr $(date +"%s" | cut -c 10) + 1`)
	rx=$(echo `expr $basex + $rtime`)
	ry=$(echo `expr $basey + $rtime`)
	adb -s ${adbclient}:5555 shell input swipe ${rx} ${ry} $(echo `expr ${rx} - 300`) ${ry}
	sleep $rtime
done

