#!/bin/sh
starttime=
sectionname=$(echo $0 | cut -d '/' -f 3 | cut -d '_' -f 1 | sed 's/^ADBRUN//')
adbclient=$(uci get adbrun.$sectionname.adbiplist)
adbport=$(uci get adbrun.$sectionname.adbport 2>/dev/null)
[ -z "$adbport" ] && adbport=5555
photopath=$(uci get adbrun.@adbinit[0].adbphotopath)
rm /tmp/adb_ADBRUN${sectionname}_.sh

if [ $(adb -s ${adbclient}:${adbport} shell getprop ro.build.version.release | cut -d '.' -f 1) -lt 6 ];then
	adb -s ${adbclient}:${adbport} shell screencap -p /data/local/tmp/screenshot.png
	adb -s ${adbclient}:${adbport} pull /data/local/tmp/screenshot.png $(uci get adbrun.@adbinit[0].adbphotopath)/screenshot${adbclient}.png
else
	adb -s ${adbclient}:${adbport} exec-out screencap -p > $(uci get adbrun.@adbinit[0].adbphotopath)/screenshot${adbclient}.png
fi
